version: '3.8'

services:
  dhcp-server:
    build: ./dhcp-server
    image: dhcp-server
    networks:
      - host-network
    volumes:
      - ./dhcp-server:/etc/dhcp
      # - dhcp-data:/var/lib/dhcp
    cap_add:
      - NET_ADMIN
    ports:
      - "67:67/udp"
    restart: unless-stopped

  dns-server:
    build: ./dns-server
    image: dns-server
    networks:
      - host-network
    volumes:
      - ./dns-server:/etc/bind
    cap_add:
      - NET_ADMIN
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
    restart: unless-stopped


networks:
  host-network:
    driver: bridge

volumes:
  dhcp-data: